#+TITLE: systemhalted's  personal emacs config
#+AUTHOR: systemhalted
#+PROPERTY: header-args :tangle yes

* sytemhalted's Emacs :noexport:
:PROPERTIES:
:VISIBILITY: children
:END:

* Table of Contents     :TOC_5_gh:
- [[#why-emacs][Why Emacs?]]
- [[#about][About]]
- [[#configurations][Configurations]]
  - [[#about-this-file][About this file]]
    - [[#org-file-tweaks][Org File Tweaks]]
      - [[#automatically-tangle][Automatically Tangle]]
      - [[#visibility-settings][Visibility Settings]]
      - [[#table-of-contents][Table of Contents]]
  - [[#global-settings][Global Settings]]
    - [[#setup-proxy][Setup Proxy]]
    - [[#garbage-collection][Garbage Collection]]
    - [[#package-configuration][Package Configuration]]
    - [[#install-and-configure-use-package][Install and Configure use-package]]
    - [[#packages][Packages]]
      - [[#ivy][Ivy]]
      - [[#magit][Magit]]
      - [[#projectile][Projectile]]
      - [[#org][Org]]
      - [[#toc-org][Toc-org]]
      - [[#org-sidebar][Org-sidebar]]
      - [[#nov-mode][Nov Mode]]
      - [[#define-word][define-word]]
      - [[#treemacs][Treemacs]]
      - [[#idle-highlight][IDLE-HIGHLIGHT]]
    - [[#communication][Communication]]
      - [[#slack][Slack]]
    - [[#keymapping][Keymapping]]
      - [[#map-caps-lock-to-ctrl][Map Caps Lock to Ctrl]]
    - [[#ui-customization][UI Customization]]
      - [[#lean-and-mean][Lean and mean]]
        - [[#disable-startupsplash-screen][Disable startup/splash screen]]
        - [[#setup-initial-major-mode-to-org-mode][Setup initial major mode to Org-mode]]
        - [[#remove-scratch-message][Remove scratch message]]
        - [[#disable-unnecessary-interface][Disable Unnecessary Interface]]
        - [[#reduce-the-delay-echoing-the-keystrokes][Reduce the delay echoing the keystrokes]]
        - [[#join-following-line][Join following line]]
        - [[#duplicate-the-current-line][Duplicate the current line]]
        - [[#full-screen][Full Screen]]
      - [[#theme][Theme]]
      - [[#fonts][Fonts]]
      - [[#forbidden-fruit][Forbidden Fruit]]
      - [[#line-numbers][Line Numbers]]
      - [[#modeline-time-and-battery][Modeline Time and Battery]]
    - [[#text-manipulation][Text Manipulation]]
      - [[#move-text][Move text]]
    - [[#string-manipulations][String manipulations]]
    - [[#shortcuts-longcuts-miscellaneous-configs][Shortcuts, Longcuts, Miscellaneous Configs]]
      - [[#clipboard-copy-from-terminal-emacs-to-the-x-clipboard][Clipboard. Copy from terminal emacs to the X clipboard.]]
      - [[#simplify-yesno-prompts][Simplify Yes/No Prompts]]
      - [[#but-make-it-hard-to-accidentally-exit][But make it hard to accidentally exit]]
      - [[#make-finding-file-easy][Make finding file easy]]
      - [[#utf-8-coding-system][UTF-8 Coding System]]
      - [[#shut-up-the-bell][Shut up the bell]]
      - [[#disabled-commands][Disabled Commands]]
    - [[#custom-functions][Custom Functions]]
      - [[#speedtest][SpeedTest]]
    - [[#programming][Programming]]
      - [[#haskell][Haskell]]
    - [[#post-initialization][Post Initialization]]
      - [[#garbage-collection-1][Garbage Collection]]

* Why Emacs?

    I started using Emacs in 2010 and my relationship with it has been on and off. I mostly use Jetbrains IntelliJ IDEA
    for my work. But the idea of Emacs - everything inside is awesome. You can configure IDEA to an extent but after that
    it just gives up. Checking emails, managing schedule, and taking notes - few things that are lacking in IDEA. Emacs
    on the other hand is an Operating System in itself. You can configure it the way you want and for your comfort and
    there is a huge community to help, guide and support you.

* About
This is my personal Emacs configuration. Over past few years, I had been using Emacs configuration by others.
I used to modify few things here and there in my old configuration but not before spending several hours and without
understanding what is going on. So, after reading =r/emacs= discussions, I decided that I will get rid of all the Emacs
configurations and start it at the very beginning. I have not used Emacs for any coding purposes. I code in Java and
IntelliJ IDEA is the best IDE for that. Therefore, I decided that in the beginning, I do not need many configurations
. Since the discussion on the =r/emacs= was all about Literate Programming and how =org-mode= facilitates that, I
decided to start with setting up org-mode first
* Configurations
** About this file 
*** Org File Tweaks
 There are a few tweaks included in this org file that make it a little easier to
 work with.

**** Automatically Tangle
 First there is a property defined on the file:

 #+BEGIN_SRC :tangle no
 header-args :tangle yes
 #+END_SRC

 This tells emacs to automatically tangle (include) all code blocks in this file when
 generating the code for the config, unless the code block explicitly includes
 =:tangle no= as the above code block does.

**** Visibility Settings
 Next we have a property that defines the visibility for org to show it's direct children on startup. This way a clean outline of all
 sub headings under Configuration is shown each time this file is opened in org-mode.

#+BEGIN_SRC :tangle no
:PROPERTIES:
:VISIBILITY: children
:END:
#+END_SRC

**** Table of Contents
 Finally, there is a [[Table of Contents][Table of Contents]] heading that includes the tag: =:TOC_3_gh:=. This
 tells an org-mode package =toc-org= to generate a table of contents under this heading
 that has a max depth of 3 and is created using Github-style hrefs. This table of contents
 is updated everytime the file is saved and makes for a functional table of contents that
 works property directly on github.

** Global Settings
*** Setup Proxy
 I use Emacs on my work laptop and there is a firewall that I need to pass through. Proxy settings allow me to do that. Save the below code under =customizations= and call it =setup-proxy.el=
;; #+INCLUDE: "~/.emacs.d/customizations/setup-proxy-template.el" src emacs-lisp :range-begin "HttpProxy" :range-end "-HttpProxy" :lines "2-11"

*** Garbage Collection
*** Package Configuration

    Define package repositories

 #+BEGIN_SRC emacs-lisp
 (require 'package)
 (setq-default
    load-prefer-newer t
    package-enable-at-startup nil)
 (add-to-list 'package-archives
              '("gnu" . "https://elpa.gnu.org/packages/") t)
 (add-to-list 'package-archives
              '("marmalade" . "http://marmalade-repo.org/packages/") t)
 (add-to-list 'package-archives
              '("tromey" . "http://tromey.com/elpa/") t)
 (add-to-list 'package-archives
              '("org" . "http://orgmode.org/elpa/") t)
 (add-to-list 'package-archives
               '("melpa" . "http://melpa.org/packages/") t)
 (add-to-list 'package-archives
              '("melpa-stable" . "http://stable.melpa.org/packages/") t)
 (package-initialize)
 #+END_SRC

*** Install and Configure use-package

 #+BEGIN_SRC emacs-lisp
 (unless (package-installed-p 'use-package)
       (package-refresh-contents)
       (package-install 'use-package t))
 (setq-default use-package-always-defer t
	       use-package-always-ensure t)
 #+END_SRC

*** Packages

**** Ivy

#+BEGIN_SRC emacs-lisp
  (use-package ivy
        :demand t)
#+END_SRC

**** Magit
 The magical git client. Let's load magit only when one of the several entry pont
 functions we invoke regularly outside of magit is called.

 #+BEGIN_SRC emacs-lisp
 
 (use-package magit
  :commands (magit-status magit-blame magit-log-buffer-file magit-log-all))

 #+END_SRC

**** Projectile
 Projectile is a quick and easy project management package that "just works". We're
 going to install it and make sure it's loaded immediately.

 #+BEGIN_SRC emacs-lisp
(use-package projectile
  :ensure t
  :bind-keymap
  ("C-c p" . projectile-command-map)
  :config
  (projectile-mode +1))
 #+END_SRC

**** Org
 Let's include a newer version of org-mode than the one that is built in. We're going
 to manually remove the org directories from the load path, to ensure the version we
 want is prioritized instead.

 #+BEGIN_SRC emacs-lisp
      (use-package org
         :ensure org-plus-contrib
         :pin org
         :defer t
         :config (setq org-log-done 'time
		       org-log-done 'note
		       org-agenda-files (list "~/org/inbox.org"
                             "~/org/gtd.org" 
                             "~/org/tickler.org"
			     "~/org/references.org")
				org-capture-templates '(("t" "Todo [inbox]" entry
							                       (file+headline "~/org/inbox.org" "Tasks")
									       "* TODO %i%?")
							                 ("T" "Tickler" entry
									       (file+headline "~/org/tickler.org" "Tickler")
									       "* %i%? \n %U"))
				org-todo-keywords '((sequence "TODO(t)" "IN-PROGRESS" "WAITING(w)" "|" "DONE(d)" "CANCELLED(c)" "HOLD(h)")))
         :init
             (define-key global-map (kbd "C-c l") 'org-store-link)
             (define-key global-map (kbd "C-c a") 'org-agenda)
             (define-key global-map (kbd "C-c c") 'org-capture)
         )

	 (setq org-refile-targets '((org-agenda-files :maxlevel . 4)
			   ("~/org/someday.org" :maxlevel . 1)
			   ("~/org/archive.org" :maxlevel . 4)
			   ))

 #+END_SRC 

**** Toc-org
Let's install and load the =toc-org= package after org mode is loaded. This is the
package that automatically generates an up to date table of contents for us.

#+BEGIN_SRC emacs-lisp
(use-package toc-org
  :after org
  :init (add-hook 'org-mode-hook #'toc-org-enable))
#+END_SRC

**** Org-sidebar
When I write, I need a map of the document or the table of content on the side. Org-sidebar helps with that:

#+BEGIN_SRC emacs-lisp
(use-package org-sidebar
  :custom (org-sidebar-tree-side 'left))
#+END_SRC

**** Nov Mode 
I prefer reading EPUB books on Emacs. Nov Mode allows me do that

#+BEGIN_SRC emacs-lisp
(use-package nov 
  :demand t)

(add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))

;; set unzip
(setq nov-unzip-program "/usr/bin/unzip") ;;nov needs to know the location of unzip package
#+END_SRC

**** define-word
Word and their meanings and what better way to have this information at point. 

#+BEGIN_SRC emacs-lisp
(use-package define-word
  :defer t
  :ensure t
  :init (global-set-key (kbd "C-c d") 'define-word-at-point)
         (global-set-key (kbd "C-c D") 'define-word))

#+END_SRC

**** Treemacs
#+BEGIN_SRC emacs-lisp
(use-package treemacs 
   :init
   (add-hook 'treemacs-mode-hook
             (lambda () (treemacs-resize-icons 15))))

#+END_SRC

**** IDLE-HIGHLIGHT

#+BEGIN_SRC emacs-lisp
(use-package idle-highlight)
#+END_SRC
*** Communication
**** Slack
#+BEGIN_SRC emacs-lisp :tangle no
  ;; I'm using use-package and el-get and evil

  ;;(el-get-bundle slack)
  (use-package slack
    :commands (slack-start)
    :init
    (setq slack-buffer-emojify t) ;; if you want to enable emoji, default nil
    (setq slack-prefer-current-team t)
    :config
    (slack-register-team
     :name "fstech-capitalone"
     :default t
     :token "xoxs-194540594981-203789560839-899883966227-30b02158c08144b0e8cae054f5ead44dad396847782b51fbd7b623e63bb6c59e"
     :subscribed-channels '(clo_microservices)
     :full-and-display-names t)

    ;; (slack-register-team
    ;;  :name "test"
    ;;  :token "xoxs-yyyyyyyyyy-zzzzzzzzzzz-hhhhhhhhhhh-llllllllll"
    ;;  :subscribed-channels '(hoge fuga))
   )
   
  (use-package alert
    :commands (alert)
    :init
    (setq alert-default-style 'notifier))
#+END_SRC

*** Keymapping

**** Map Caps Lock to Ctrl
#+BEGIN_SRC emacs-lisp :tangle no
(mac-control-modifier)
#+END_SRC
*** UI Customization

Some of these settings were copied from Sergei Nosov's [[https://github.com/snosov1/dot-emacs#ui-customization][configurations.]]

**** Lean and mean
Emacs doesn’t need a lot of UI elements - it should be lean and mean. Well, and clean. 
***** Disable startup/splash screen
#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-screen t)
#+END_SRC

***** Setup initial major mode to Org-mode
#+BEGIN_SRC emacs-lisp 
(setq-default initial-major-mode (quote org-mode))
#+END_SRC

***** Remove scratch message
#+BEGIN_SRC emacs-lisp
(setq-default initial-scratch-message nil)
#+END_SRC

***** Disable Unnecessary Interface
#+BEGIN_SRC emacs-lisp
(menu-bar-mode -1)
(unless (and (display-graphic-p) (eq system-type 'darwin))
  (push '(menu-bar-lines . 0) default-frame-alist))
(push '(tool-bar-lines . 0) default-frame-alist)
(push '(vertical-scroll-bars) default-frame-alist)
#+END_SRC
***** Reduce the delay echoing the keystrokes
When you press C-x, for example, and hesitate with a next character, C-x will be displayed in the echo-area after some time. But I don’t see any reason why you should wait for it.
#+BEGIN_SRC emacs-lisp
(setq echo-keystrokes 0.001)
#+END_SRC
***** Join following line

#+BEGIN_SRC emacs-lisp
(define-key global-map (kbd "C-c j")
  (defun join-following-line (arg)
    "Joins the following line or the whole selected region"
    (interactive "P")
    (if (use-region-p)
        (let ((fill-column (point-max)))
          (fill-region (region-beginning) (region-end)))
      (join-line -1))))
#+END_SRC

***** Duplicate the current line
Equivalent of Ctrl+d (Command+d on Mac)
Source: https://www.emacswiki.org/emacs/CopyingWholeLines#toc12

#+BEGIN_SRC emacs-lisp 
(define-key global-map (kbd "C-c k")
  (defun duplicate-line-or-region (&optional n)
      "Duplicate current line, or region if active.
    With argument N, make N copies.
    With negative N, comment out original line and use the absolute value."
      (interactive "*p")
      (let ((use-region (use-region-p)))
        (save-excursion
          (let ((text (if use-region        ;Get region if active, otherwise line
                          (buffer-substring (region-beginning) (region-end))
                        (prog1 (thing-at-point 'line)
                          (end-of-line)
                          (if (< 0 (forward-line 1)) ;Go to beginning of next line, or make a new one
                              (newline))))))
            (dotimes (i (abs (or n 1)))     ;Insert N times, or once if not specified
              (insert text))))
        (if use-region nil                  ;Only if we're working with a line (not a region)
          (let ((pos (- (point) (line-beginning-position)))) ;Save column
            (if (> 0 n)                             ;Comment out original with negative arg
                (comment-region (line-beginning-position) (line-end-position)))
            (forward-line 1)
            (forward-char pos))))))
#+END_SRC

***** Full Screen
#+BEGIN_SRC emacs-lisp
  (toggle-frame-fullscreen)
  (add-to-list 'default-frame-alist '(fullscreen . fullboth))
;;(add-hook 'window-setup-hook 'toggle-frame-maximized t).
#+END_SRC

#+RESULTS:
: ((fullscreen . maximized))

**** Theme

#+BEGIN_SRC emacs-lisp :tangle no
(use-package ample-theme 
  :init (progn (load-theme 'ample t t)
               (load-theme 'ample-flat t t)
               (load-theme 'ample-light t t)
               (enable-theme 'ample-light))
  :defer t
  :ensure t)
#+END_SRC

#+BEGIN_SRC emacs-lisp :tangle no
(use-package spacemacs-common
    :ensure spacemacs-theme
    :config (load-theme 'spacemacs-light t))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package leuven-theme
   :config (load-theme 'leuven t))
#+END_SRC

**** Fonts

DejaVu fonts family is the best one out there. And DejaVu Sans Mono is its brightest child:

- it’s sans-serif
- it’s mono-space
- it covers a great amount of Unicode symbols
- it’s community-driven and MIT/public domain licensed
- it makes l, 1 and I clearly distinguishable, as well as 0 and O
- it’s beautiful

Basically, DejaVu Sans Mono is a “font done right” for technical work.

NOTE: This has been disabled because it messes up some of the things like the embedded calendar

#+BEGIN_SRC emacs-lisp :tangle no
(set-face-attribute 'default nil :family "DejaVu Sans Mono")
(set-face-attribute 'default nil :height 165)
#+END_SRC

**** Forbidden Fruit
This setting modifies the Mac key to act like Meta key. I am just keeping it here for reference. I am not going to modify it though. See /:tangle no/, it will not put it in the compiled /emacs.el/ file.

#+BEGIN_SRC emacs-lisp :tangle no
(setq-default mac-command-modifier 'meta)
#+END_SRC 
**** Line Numbers
Display line numbers, and column numbers in modeline.

#+BEGIN_SRC emacs-lisp                                                                                            
;; Hook line numbers to only when files are opened, also use linum-mode for emacs-version< 26
(if (version< emacs-version "26")
    (global-linum-mode)
  (add-hook 'text-mode-hook #'display-line-numbers-mode)
  (add-hook 'prog-mode-hook #'display-line-numbers-mode))
;; Display column numbers in modeline
(column-number-mode 1)                                                                                     
#+END_SRC
**** Modeline Time and Battery
#+BEGIN_SRC emacs-lisp
(display-time-mode 1)
(display-battery-mode 1)

#+END_SRC

*** Text Manipulation
**** Move text
Most of the time, I need to move a the text up an down a bit. There is a /transpose-line/ command that maps to /C-x C-t/, which is cumbersome and most of the time it messes-up with my flow. So, here we will map it to /M-n/ and /M-p/ following the convention of movement keys. 
Note: If you need to move the text to some pretty distant place, then, of course, it’s easier to kill and yank it.

#+BEGIN_SRC emacs-lisp
(eval-after-load "move-text-autoloads"
  '(progn
     (if (require 'move-text nil t)
         (progn
           (define-key global-map (kbd "M-n") 'move-text-down)
           (define-key global-map (kbd "M-p") 'move-text-up))
       (message "WARNING: move-text not found"))))
#+END_SRC

*** String manipulations
Emacs 24.4 came with a subr-x library with routines for string manipulations, like string-trim, string-join and etc. It’s better to always have these at hand.

#+BEGIN_SRC emacs-lisp
(require 'subr-x nil t)
#+END_SRC

*** Shortcuts, Longcuts, Miscellaneous Configs
**** Clipboard. Copy from terminal emacs to the X clipboard.
#+BEGIN_SRC emacs-lisp
(use-package xclip
  :ensure t
  :config
  (xclip-mode 1))

#+END_SRC
**** Simplify Yes/No Prompts
#+BEGIN_SRC emacs-lisp
(fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC

**** But make it hard to accidentally exit
#+BEGIN_SRC emacs-lisp
(setq-default confirm-kill-emacs (quote y-or-n-p))
#+END_SRC

**** Make finding file easy
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x f")    'find-file)
#+END_SRC

**** UTF-8 Coding System
Use UTF-8 as much as possible with unix line endings.
**** Shut up the bell
#+BEGIN_SRC emacs-lisp
(setq ring-bell-function 'ignore) ;; shut up the bell
#+END_SRC

**** Disabled Commands
Change nil to t to disable the command. 
Note: currently not using it. But this is the way to do it
#+BEGIN_SRC emacs-lisp :tangle no
(put 'upcase-region 'disabled nil) 
#+END_SRC

*** Custom Functions
**** SpeedTest
#+BEGIN_SRC emacs-lisp
(load "setup-speedtest.el")
#+END_SRC

*** Programming
**** Haskell

#+BEGIN_SRC emacs-lisp :tangle no
(use-package haskell-mode
  :defer t
  :init
  (progn
    (add-hook 'haskell-mode-hook #'haskell-indentation-mode)
    (add-hook 'haskell-mode-hook #'turn-on-haskell-doc-mode)
    (add-hook 'haskell-mode-hook #'subword-mode))
  :config
  (progn
    (let ((my-cabal-path (expand-file-name "~/.cabal/bin")))
      (setenv "PATH" (concat my-cabal-path ":" (getenv "PATH")))
      (add-to-list 'exec-path my-cabal-path))
    (custom-set-variables '(haskell-tags-on-save t))

    (custom-set-variables
     '(haskell-process-suggest-remove-import-lines t)
     '(haskell-process-auto-import-loaded-modules t)
     '(haskell-process-log t))
    (define-key haskell-mode-map (kbd "C-c C-l")
      'haskell-process-load-or-reload)
    (define-key haskell-mode-map (kbd "C-c C-z")


    (eval-after-load 'haskell-cabal
      '(progn
         (define-key haskell-cabal-mode-map (kbd "C-c C-z")
           'haskell-interactive-switch)
         (define-key haskell-cabal-mode-map (kbd "C-c C-k")
           'haskell-interactive-mode-clear)
         (define-key haskell-cabal-mode-map (kbd "C-c C-c")
           'haskell-process-cabal-build)
         (define-key haskell-cabal-mode-map (kbd "C-c c")
           'haskell-process-cabal)))

    (custom-set-variables '(haskell-process-type 'cabal-repl))

    (autoload 'ghc-init "ghc" nil t)
    (autoload 'ghc-debug "ghc" nil t)
    (add-hook 'haskell-mode-hook (lambda () (ghc-init)))))
#+END_SRC

*** Post Initialization
**** Garbage Collection
Let's lower our GC thresholds back down to a sane level.

#+BEGIN_SRC emacs-lisp
(setq gc-cons-threshold 16777216
      gc-cons-percentage 0.1)
#+END_SRC
