(require 'projectile)
(projectile-mode +1)
(define-key projectile-mode-map (kbd "C-p") 'projectile-command-map)
;;(define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)
(setq projectile-project-search-path '("~/Workspace/" "~/workspace/"))
